### ISSUE TITLE
Expression to select topics

### ISSUE THREAD

**Issue by vitoravancini** [krallistic/kafka-prometheus-exporter#2]
It would be useful( at least in my use case) to have an expression to select topics. There are a lot of topics that I don't intend to monitor in our current kafka deployment. I've already implemented this filter, would you be interested in a pull request with this code?

**Comment by krallistic** [comment]
Yes, sure.

**Comment by vitoravancini** [comment]
Ok,  just created it. Thanks.

**Comment by krallistic** [comment]
Merged, thanks for the PR :)
